Patch for corner case of empty addition (#84)
* Insert cutting planes rules interface

* cutting_planes: Created simplest working examples

* cp_multiplcation: New tests and asserts

* cutting planes: Add arguments check

* cutting_planes: Opening the pbsum list

* cutting planes: Checking coeffs (albeit move error)

* cutting planes: Finished cp_multiplication assert sequence

* cutting planes: Avoiding scalar clones

* Insert HashMap into cp_multiplication

* Add saturation check with hashmap

* Add cp_division checker (partial)

* Created tests for cp_addition

* cp_addition checker with hashmap

* extract method `unwrap_pseudoboolean_inequality`

* Implement ceildiv in cp_division

* Increased cp_saturation test cases

* Increased test cases for cp_multiplication

* Increase test cases for cp_division

* Add addition test cases and extract method

* Cutting Planes Add support for negated literals

* Comment cp_addition next step

* Add method is_negated_literal

* Implemented cp_addtion with reduction and slack

* Add Rust devcontainer for remote development

* cp_addtion fixed edge case for reduction

* Remove old comments

* cutting planes: remove `as_term()` call on `Rc<Term>`

* Fix typo in cutting_planes

* [rules] [pb_blasting] Create module and add dummy `pbblast_bveq` code

* [rules] [pb_blasting] Add all pbblast function bodies and small test case

* [ast] [parser] [pb_blasting] Add the `int_of` constructor for pseudo-boolean bitvector extraction

* [ast] [parser] [pb_blasting] Add the `pbbterm` constructor for bitvector creation from pseudo booleans (Int)

* [checker] [pb_blasting] Checking of `pbblast_bveq`

* [pb_blasting] Commenting better the pbblast_bveq function

* [ast] Qualify usage of `Constant` for better support at `build_term!` macro

* [rules] [pb_blasting] Add ability to omit the coefficient 1 at `pbblast_bveq`

* [pb_blasting] Reformulated checking for `pbblast_bvult` rule, add new commented tests

* [pb_blasting] Added checking and rules for `bvugt`, `bvuge` and `bvule`, and test cases

* [pb_blasting] Add 8-bit unit tests

* [pb_blasting] Separate test cases by bit width

* [pb_blasting] Created unit test for `pbblast_bvand`

* [pb_blasting] Created unit test for `pbblast_bvxor`

* [pb_blasting] Created unit test for `pbblast_bvslt`

* [debug] Setup unit test debug with LLDB

* [pb_blasting] Started checking `bvslt`

* [pb_blasting] First tests for `pbbvar` and `pbbconst`

* [pb_blasting] Added more unit tests for `pbblast_pbbvar` and `pbblast_pbbconst`

* [pb_blasting] Implement `pbblast_pbbvar` checker, had to disable "parser error" test cases

* [pb_blasting] Create implementation fro `pbblast_pbbconst` (partial)

* [pb_blasting] Remove test cases that aren't well typed

* [pb_blasting] Changed the tests of pbbconst for the simpler expression

* [pb_blasting] Implement the rule `pbblast_pbbconst` passing the tests

* [pb_blasting] Convert `Unspecified` errors into `Explanation` errors

* [cutting_planes] Convert `Unspecified` errors into `Explanation` errors

* [pb_blasting] Change endianess of signed pbblasting Rules

* [pb_blasting] Change the Endianness of rules and tests

* [testing] Extend the `run_tests` function to output the `Explanation` message

* [ref] Fix typo in term.rs

* [dev] Explain better the test fail reasons

* [pb_blasting] Implement `pbblast_bvslt` checker, with new unit tests

* [pb_blasting] Added test cases for `bvsgt`, `bvsge` and `bvsle`

* [pb_blasting] Implement the `pbblast_bvsle` rule with a helper

* [pb_blasting] Implement the `pbblast_bvsgt` and `pbblast_bvsge` rules

* [pb_blasting] Fix the tests for `pbblast_bvxor`

* [pb_blasting] Implement the `pbblast_bvxor` rule with helpers `get_bit_width` and `assert_bitvector_indexing`

* [pb_blasting] Fix the shape of `bvand` tests

* [pb_blasting] Implement the `pbblast_bvand` rule

* [pb_blasting] Removed backticks from comments because they are interpreted as test cases

* [pb_blasting] Fix the `error[E0658]: use of unstable library feature 'slice_first_last_chunk'`

* [lint] Changes asked by `clippy` linter

* [ref] Remove environment specific settings

* Update `bveq` and `bvult` without trailing 0

* Patch tests of `bvugt`

* Patch of `bvugt`

* Patch `bvuge` for trailing 0

* Path of `bvule`

* Path tests of `bvslt_2`

* Patched `bvslt`

* Patch `bvsgt`

* Patch `bvsge`

* Patch `bvsle`

* Remove unused `range`

* Short-circuiting for`bveq`

* Change constant check to match term

* Understanding choice

* Add the `@`s

* Bvand with choice
Still need to check binding z

* Add support for singleton pbsum

* Update cutting planes test cases

* Added support for single 0 in pbineq

* Moving code to align with production

* Add small test case

* Fix linting

* Changes in pb_blasting to match merged code

* Adapting bvxor with choice

* Shortened assertions with assert_eq

* Add rust-analyzer configuration changes

* Fixed the tests of `bvxor`

* Removed .vscode again for compatible checkouts

* Aiding the clipper linter

* Align with main

* Add tests for `cp_addtion` with empty sum